# 监听本地的端口
listen: :8080

# 使用redis来存放access_token
redis:
  host: 127.0.0.1:6379

# 微信公众号相关配置
officialAccountConfig:
  appID: wx466e9a8793ecf7ed
  appSecret: 0da278071fe575fa59de4795c7eb2e4d
  token: testtoken